USE syshes;

INSERT INTO modules VALUES
(1, 'fa-solid fa-user', 'user', 'Usuários'),
(2, 'fa-solid fa-gears', 'module', 'Módulos'),
(3, 'fa-solid fa-user-injured', 'patient', 'Pacientes'),
(4, 'fa-solid fa-location-dot', 'origin', 'Origens'),
(5, 'fa-solid fa-truck-medical', 'entry', 'Entradas');

INSERT INTO users VALUES
(1, 'Administrador', '000.000.000-00', '(96) 99999-9999', 'cotec@saude.ap.gov.br', '$2y$10$xQFEDHKyL8xIJzKOc1XVQ.sxzyoYkaF2LhDWo5PYVYFJorOtYJSPK', '["1", "2", "3", "4", "5"]', 1, 0);

INSERT INTO origins VALUES
(1, 'AREA RURAL', 1),
(2, 'CASA', 1),
(3, 'CASAI - CASA DE APOIO À SAÚDE INDÍGENA', 1),
(4, 'CIOSPE', 1),
(5, 'CREAP - CENTRO DE REABILITAÇÃO DO AMAPÁ', 1),
(6, 'ESCOLA', 1),
(7, 'HCA - HOSPITAL DA CRIANÇA E DO ADOLESCENTE', 1),
(8, 'HCAL - HOSPITAL DE CLINICAS DR. ALBERTO LIMA', 1),
(9, 'HE - HOSPITAL DE EMERGÊNCIA', 1),
(10, 'HEAP - HOSPITAL DO AMAPÁ', 1),
(11, 'HEC - HOSPITAL DE CALÇOENE', 1),
(12, 'HELJ - HOSPITAL DE LARANJAL DO JARI', 1),
(13, 'HEMD - HOSPITAL DE MONTE DOURADO', 1),
(14, 'HEO - HOSPITAL DE OIAPOQUE', 1),
(15, 'HES - HOSPITAL DE SANTANA', 1),
(16, 'HEVJ - HOSPITAL DE VITÓRIA DO JARÍ', 1),
(17, 'HMML - HOSPITAL DA MULHER MÃE LUZIA', 1),
(18, 'HOSPITAL SÃO CAMILO E SÃO LUIZ', 1),
(19, 'HOSPITAL UNIMED', 1),
(20, 'IAPEN', 1),
(21, 'NÃO INFORMADO', 1),
(22, 'PAI - PRONTO ATENDIMENTO INFANTIL', 1),
(23, 'TRABALHO', 1),
(24, 'UBS ALVARO CORRÊA', 1),
(25, 'UBS CONGÓS', 1),
(26, 'UBS DO MUNICIPIO DO AMAPÁ', 1),
(27, 'UBS DO MUNICIPIO DE CALÇOENE', 1),
(28, 'UBS DO MUNICIPIO DE CUTIAS', 1),
(29, 'UBS DO MUNICIPIO DE FERREIRA GOMES', 1),
(30, 'UBS DO MUNICIPIO DE ITAUBAL', 1),
(31, 'UBS DO MUNICIPIO DE LARANJAL DO JARI', 1),
(32, 'UBS DO MUNICIPIO DE MACAPÁ', 1),
(33, 'UBS DO MUNICIPIO DE MAZAGÃO', 1),
(34, 'UBS DO MUNICIPIO DE OIAPOQUE', 1),
(35, 'UBS DO MUNICIPIO DE PEDRA BRANCA DO AMAPARÍ', 1),
(36, 'UBS DO MUNICIPIO DE PORTO GRANDE', 1),
(37, 'UBS DO MUNICIPIO DE PRACUÚBA', 1),
(38, 'UBS DO MUNICIPIO DE SANTANA', 1),
(39, 'UBS DO MUNICIPIO DE SERRA DO NAVIO', 1),
(40, 'UBS DO MUNICIPIO DE TARTARUGALZINHO', 1),
(41, 'UBS DO MUNICÍPIO DE VITÓRIA DO JARI', 1),
(42, 'UBS LÉLIO SILVA', 1),
(43, 'UBS PERPETUO SOCORRO', 1),
(44, 'UBS RUBEN ARONOVITCH', 1),
(45, 'UBS/UPA MARCELO CÂNDIA', 1),
(46, 'UPA DE LARANJAL DO JARI', 1),
(47, 'UPA ZONA NORTE', 1),
(48, 'UPA ZONA SUL', 1),
(49, 'VIA PÚBLICA', 1);

INSERT INTO patients (name, active) VALUES
('PACIENTE DESCONHECIDO', 1);
